Gerenciamento-Contatos/Models/ContatoModel.cs
using System.ComponentModel.DataAnnotations;

namespace ControleDeContatos.Models
{
    public class Contato
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "O nome é obrigatório")]
        public string? Nome { get; set; }

        [Required(ErrorMessage = "O telefone é obrigatório")]
        public string? Telefone { get; set; }

        [Required(ErrorMessage = "O e-mail é obrigatório")]
        [EmailAddress(ErrorMessage = "Digite um e-mail válido")]
        public string? Email { get; set; }
    }
}

Gerenciamento-Contatos/Models/ErrorViewModel.cs
namespace Gerenciamento_Contatos.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Gerenciamento-Contatos/Controllers/ContatosController.cs
using ControleDeContatos.Models;
using ControleDeContatos.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace Contatos.Controllers
{
    public class ContatosController : Controller
    {
        private readonly IContatoRepositorio _contatoRepositorio;

        public ContatosController(IContatoRepositorio contatoRepositorio)
        {
            _contatoRepositorio = contatoRepositorio;
        }

        public ActionResult Index()
        {
            return View();  
        }

        public ActionResult Criar()
        {
            return View();  
        }

        public ActionResult Editar()
        {
            return View();
        }

        public ActionResult ApagarConfirmacao()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Criar(Contato contato)
        {
            if (ModelState.IsValid)
            {
                _contatoRepositorio.Adicionar(contato);
                return RedirectToAction("Index");
            }
            return View(contato);
        }
    }
}

Gerenciamento-Contatos/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Gerenciamento_Contatos.Models;

namespace Gerenciamento_Contatos.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Gerenciamento-Contatos/Views/Contatos/ApagarConfirmacao.cshtml
@{
    ViewData["Title"] = "Confirmação de apagar contato";
}
<div class="text-center">
<h3>Realmente deseja apagar esse contato (Vinicius Antnio De Oliveira)</h3>
</div>
<a class="btn btn-primary" role="button" asp-controller="Contatos" asp-action="Index">Cancelar exclusão</a>
<a class="btn btn-primary" role="button" asp-controller="Contatos" asp-controller="Apagar">Confirmar exclusão</a>

Gerenciamento-Contatos/Views/Contatos/Criar.cshtml
@model ControleDeContatos.Models.Contato

<div class="text-center">
    <h1 class="display-4">Cadastrar Contato</h1>
</div>

<form asp-action="Criar" method="post">
    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome do contato">
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="email">Email</label>
        <input type="email" asp-for="Email" class="form-control" placeholder="Digite o e-mail do contato">
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="telefone">Número do contato</label>
        <input type="text" asp-for="Telefone" class="form-control" placeholder="Digite o número do contato">
        <span asp-validation-for="Telefone" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Adicionar</button>
    <a class="btn btn-secondary" asp-controller="Contatos" asp-action="Index" role="button">Voltar</a>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Gerenciamento-Contatos/Views/Contatos/Editar.cshtml
<div class="text-center">

  <h1 class="Display-4">Editar Contato</h1>
  
</div>

<form>
  <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" class="form-control" placeholder="Digite o nome do contato"> 
  </div>
  <div class="form-group">
        <label for="email">Email</label>
        <input type="text" class="form-control" placeholder="Digite o e-mail do contato">
  </div>
    <div class="form-group">
        <label for="telefone">Numero do contato</label>
        <input type="text" class="form-control" placeholder="Digite o número do contato">
  </div>

  <button type="submit" class="btn btn-primary">Alterar</button>
  <a class="btn btn-secondary" asp-controller="Contatos" asp-action="Index" role="button">Voltar</a>
</form>

Gerenciamento-Contatos/Views/Contatos/Index.cshtml
@{
    Layout = "_Layout"; // Referencia o layout no Shared
}

@* Index.cshtml *@
@{
    ViewData["Title"] = "Lista de Contatos";
}
<div class="text-center">
  <div class="d-grid gap-2 d-md-flex justify-content-md-start">
    <a class="btn btn-primary" role="button" asp-controller="Contatos" asp-action="Criar">Adicionar novo contato</a>
  </div>
  <br />

  <h1>@ViewData["Title"]</h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nome</th>
        <th scope="col">Email</th>
        <th scope="col">Celular</th>
        <th scope="col">Celular</th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
      <tr>
        <th scope="row">1</th>
        <td>Mark</td>
        <td>Otto@gmail.com</td>
        <td>43 99875-3434</td>
        <td>
          <div class="btn-group" role="group">
          <a role="button" class="btn btn-primary" asp-controller="Contatos" asp-action="ApagarConfirmacao">Apagar</a>
          <a role="button" class="btn btn-danger" asp-controller="Contatos" asp-action="Editar">Editar</a>
          </div>
      </td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Jacob</td>
      <td>Thornton@gmail.com</td>
      <td>43 99875-3434</td>
      <td> <div class="btn-group" role="group">
        <a role="button" class="btn btn-primary" asp-controller="Contatos" asp-action="ApagarConfirmacao">Apagar</a>
        <a role="button" class="btn btn-danger" asp-controller="Contatos" asp-action="Editar">Editar</a>
          </div>
    </td>
    </tr>
        <tr>
      <th scope="row">3</th>
      <td>Jacob</td>
      <td>jacob@gmail.com</td>
      <td>43 99875-3434</td>
      <td> <div class="btn-group" role="group">
        <a role="button" class="btn btn-primary" asp-controller="Contatos" asp-action="ApagarConfirmacao">Apagar</a>
        <a role="button" class="btn btn-danger" asp-controller="Contatos" asp-action="Editar">Editar</a>
          </div>
    </td>
    </tr>
    
  </tbody>
</table>
</div>

Gerenciamento-Contatos/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Páginal Inicial";
}

<div class="text-center">
    <h1 class="display-4">Bem Vindo!</h1>
    <p>Sistema De Gerenciamento De Contatos</p>
</div>

Gerenciamento-Contatos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gerenciamento_Contatos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Gerenciamento_Contatos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gerenciamento_Contatos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contatos" asp-action="Index">Contatos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Gerenciamento_Contatos
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>